name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alphax123/docker-image-autobuild:latest
    - name: Push the Docker image
      run: docker login -u ijn35807 -p ${{ secrets.DOCKER_TOKEN }} && docker push alphax123/docker-image-autobuild:latest
